services:
  chromadb:
    image: chromadb/chroma:latest
    container_name: chromadb
    ports:
      - "8000:8000"
    environment:
      - CHROMA_DB_IMPL="duckdb+parquet"
      - CHROMA_SERVER_AUTHN="none"
    volumes:
      - chroma_data:/data
    restart: unless-stopped
volumes:
  chroma_data: